service: video-transcoder-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    basePath: ./
    REDIS_URL: ${env:REDIS_URL}
    MONGO_URI: ${env:MONGO_URI}
    MY_AWS_ACCESS_KEY_ID: ${env:MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${env:MY_AWS_SECRET_ACCESS_KEY}
    TEMP_S3_BUCKET_NAME: ${env:TEMP_S3_BUCKET_NAME}
    FINAL_S3_BUCKET_NAME: ${env:FINAL_S3_BUCKET_NAME}
    WEBHOOK_URL: ${env:WEBHOOK_URL}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

functions:
  api:
    handler: ./src/index.handler
    events:
      - httpApi: '*'
