service: video-transcoder-server
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    basePath: ./
    REDIS_URL: ${env:REDIS_URL}
    MONGO_URI: ${env:MONGO_URI}
    MY_AWS_ACCESS_KEY_ID: ${env:MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${env:MY_AWS_SECRET_ACCESS_KEY}
    TEMP_S3_BUCKET_NAME: ${env:TEMP_S3_BUCKET_NAME}
    FINAL_S3_BUCKET_NAME: ${env:FINAL_S3_BUCKET_NAME}
    WEBHOOK_URL: ${env:WEBHOOK_URL}
    CLUSTER: ${env:CLUSTER}
    TASK: ${env:TASK}
    CORS_ORIGIN: ${env:CORS_ORIGIN}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    GOOGLE_CALLBACK_URL: ${env:GOOGLE_CALLBACK_URL}
    FRONTEND_URL: ${env:FRONTEND_URL}
    SESSION_SECRET: ${env:SESSION_SECRET}


plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

functions:
  api:
    handler: ./src/index.handler
    events:
      - httpApi: "*"
